--------------------------------------------------------
--  File created - Monday-February-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."ADDRESS" 
   (	"ADDRESS_ID" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"POSTCODE" VARCHAR2(20 BYTE), 
	"CUST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."ADMINS" 
   (	"ADMIN_ID" NUMBER(5,0), 
	"ADMIN_PHONE" VARCHAR2(12 BYTE), 
	"ADMIN_NAME" VARCHAR2(50 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARTS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."CARTS" 
   (	"CART_ID" NUMBER(5,0), 
	"CUST_ID" NUMBER(5,0), 
	"MENU_ID" NUMBER(5,0), 
	"QUANTITY" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."CUSTOMERS" 
   (	"CUST_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CUST_PASSWORD" VARCHAR2(255 BYTE), 
	"REG_DATE" DATE, 
	"PHONE_NO" VARCHAR2(255 BYTE), 
	"DELIVERY_ADDRESS" VARCHAR2(255 BYTE), 
	"CUST_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."MENU" 
   (	"MENU_ID" NUMBER, 
	"MENU_NAME" VARCHAR2(255 BYTE), 
	"MENU_PRICE" FLOAT(126), 
	"MENU_DESCRIPTION" VARCHAR2(255 BYTE), 
	"MENU_QUANTITY" NUMBER, 
	"MENU_IMAGE" VARCHAR2(20 BYTE), 
	"CATEGORY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU_CATEGORY
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."MENU_CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."ORDER_DETAILS" 
   (	"ORDER_DETAILS_ID" NUMBER(5,0), 
	"ORDER_ID" NUMBER(5,0), 
	"MENU_ID" NUMBER(5,0), 
	"QUANTITY" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_STATUS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."ORDER_STATUS" 
   (	"STATUS_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_TIME" DATE, 
	"DELIVERY_TIME" DATE, 
	"COMPLETE_TIME" DATE, 
	"ADMIN_ID" NUMBER, 
	"RIDER_ID" NUMBER, 
	"CUST_ID" NUMBER(5,0), 
	"STATUS_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"METHOD_ID" NUMBER, 
	"PAYMENT_TIME" DATE, 
	"TOTAL_PAYMENT" NUMBER(*,0), 
	"DELIVERY_CHARGE" NUMBER(*,0), 
	"ORDER_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENT_METHOD
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."PAYMENT_METHOD" 
   (	"METHOD_ID" NUMBER, 
	"METHOD_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RIDER
--------------------------------------------------------

  CREATE TABLE "HENSHIN"."RIDER" 
   (	"RIDER_ID" NUMBER, 
	"RIDER_NAME" VARCHAR2(20 BYTE), 
	"RIDER_IC" VARCHAR2(20 BYTE), 
	"RIDER_PHONE" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"PLATE_NO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HENSHIN.ADDRESS
SET DEFINE OFF;
Insert into HENSHIN.ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE,POSTCODE,CUST_ID) values ('1','No.76 Jalan BK6E/2','Bandar Kinrara','Selangor','47180',1);
Insert into HENSHIN.ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE,POSTCODE,CUST_ID) values ('2','No. 55 Jalan BK5/11D','Shah Alam','Shah Alam','43800',2);
Insert into HENSHIN.ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE,POSTCODE,CUST_ID) values ('3','No. 89 Jalan Kampung Indah','Bangi','Kuala Lumpur','48000',1);
REM INSERTING into HENSHIN.ADMINS
SET DEFINE OFF;
Insert into HENSHIN.ADMINS (ADMIN_ID,ADMIN_PHONE,ADMIN_NAME,ADMIN_PASSWORD,EMAIL) values (1,'0173414885','Haziqah','haziqah123','haziqah@gmail.com');
Insert into HENSHIN.ADMINS (ADMIN_ID,ADMIN_PHONE,ADMIN_NAME,ADMIN_PASSWORD,EMAIL) values (2,'01123456789','Syazana','syazana123','syazana@gmail.com');
REM INSERTING into HENSHIN.CARTS
SET DEFINE OFF;
REM INSERTING into HENSHIN.CUSTOMERS
SET DEFINE OFF;
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('haziqah','iqasimfoni@gmail.com','1234',to_date('09-FEB-21','DD-MON-RR'),'0184714660',null,41);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('its571','571@test','123456',to_date('26-FEB-21','DD-MON-RR'),'0123456789',null,44);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('mira','mira@99','1234',to_date('05-JAN-21','DD-MON-RR'),'018471',null,1);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('momotaro','iqasimfoni@gmail.com','asilacomel',to_date('03-JAN-21','DD-MON-RR'),'123456',null,3);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('testting data','mazni@rocketweb.my','asilacomel',to_date('03-DEC-20','DD-MON-RR'),'0184714660',null,21);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('miraaa','mirahaziq99@gmail.com','123465',to_date('05-OCT-20','DD-MON-RR'),'123456',null,45);
Insert into HENSHIN.CUSTOMERS (CUST_NAME,EMAIL,CUST_PASSWORD,REG_DATE,PHONE_NO,DELIVERY_ADDRESS,CUST_ID) values ('amirah','amirahaziqah99@gmail.com','1234',to_date('03-AUG-20','DD-MON-RR'),'0184714660',null,2);
REM INSERTING into HENSHIN.MENU
SET DEFINE OFF;
Insert into HENSHIN.MENU (MENU_ID,MENU_NAME,MENU_PRICE,MENU_DESCRIPTION,MENU_QUANTITY,MENU_IMAGE,CATEGORY_ID) values (1,'Chocolate Cake',105,'Chocolate cake topped with chocolate ganache, strawberries and pomegranate.',1,null,1);
Insert into HENSHIN.MENU (MENU_ID,MENU_NAME,MENU_PRICE,MENU_DESCRIPTION,MENU_QUANTITY,MENU_IMAGE,CATEGORY_ID) values (2,'Chocolate Lemon Cake',89,'A great combination of chocolate and lemon that will shock whoever eat it, a really tasty cake.',1,null,1);
REM INSERTING into HENSHIN.MENU_CATEGORY
SET DEFINE OFF;
Insert into HENSHIN.MENU_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (1,'Wholecakes');
Insert into HENSHIN.MENU_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (2,'Cupcake');
Insert into HENSHIN.MENU_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (3,'Cookies');
Insert into HENSHIN.MENU_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (4,'Dessert');
REM INSERTING into HENSHIN.ORDER_DETAILS
SET DEFINE OFF;
REM INSERTING into HENSHIN.ORDER_STATUS
SET DEFINE OFF;
Insert into HENSHIN.ORDER_STATUS (STATUS_ID,STATUS) values (1,'PENDING');
Insert into HENSHIN.ORDER_STATUS (STATUS_ID,STATUS) values (2,'PREPARING');
Insert into HENSHIN.ORDER_STATUS (STATUS_ID,STATUS) values (3,'DELIVERING');
Insert into HENSHIN.ORDER_STATUS (STATUS_ID,STATUS) values (4,'DELIVERED');
REM INSERTING into HENSHIN.ORDERS
SET DEFINE OFF;
Insert into HENSHIN.ORDERS (ORDER_ID,ORDER_TIME,DELIVERY_TIME,COMPLETE_TIME,ADMIN_ID,RIDER_ID,CUST_ID,STATUS_ID) values (1,null,null,null,null,null,1,null);
Insert into HENSHIN.ORDERS (ORDER_ID,ORDER_TIME,DELIVERY_TIME,COMPLETE_TIME,ADMIN_ID,RIDER_ID,CUST_ID,STATUS_ID) values (2,null,null,null,null,null,2,null);
REM INSERTING into HENSHIN.PAYMENT
SET DEFINE OFF;
REM INSERTING into HENSHIN.PAYMENT_METHOD
SET DEFINE OFF;
Insert into HENSHIN.PAYMENT_METHOD (METHOD_ID,METHOD_NAME) values (1,'CASH ON DELIVERY');
Insert into HENSHIN.PAYMENT_METHOD (METHOD_ID,METHOD_NAME) values (2,'ONLINE BANKING');
REM INSERTING into HENSHIN.RIDER
SET DEFINE OFF;
Insert into HENSHIN.RIDER (RIDER_ID,RIDER_NAME,RIDER_IC,RIDER_PHONE,REG_DATE,STATUS,PASSWORD,PLATE_NO,EMAIL) values (2,'unknown','12345','02456',to_date('06-JAN-21','DD-MON-RR'),'Active','1234','JSP3456','test@gmail.com');
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."ADDRESS_PK" ON "HENSHIN"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007367
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."SYS_C007367" ON "HENSHIN"."ADMINS" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."CARTS_PK" ON "HENSHIN"."CARTS" ("CART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."CUSTOMERS_PK" ON "HENSHIN"."CUSTOMERS" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."MENU_PK" ON "HENSHIN"."MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."MENU_CATEGORY_PK" ON "HENSHIN"."MENU_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."ORDER_DETAILS_PK" ON "HENSHIN"."ORDER_DETAILS" ("ORDER_DETAILS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."ORDER_STATUS_PK" ON "HENSHIN"."ORDER_STATUS" ("STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."ORDERS_PK" ON "HENSHIN"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."PAYMENT_UK1" ON "HENSHIN"."PAYMENT" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_METHOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."PAYMENT_METHOD_PK" ON "HENSHIN"."PAYMENT_METHOD" ("METHOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RIDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENSHIN"."RIDER_PK" ON "HENSHIN"."RIDER" ("RIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADDRESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."ADDRESS_TRG" 
BEFORE INSERT ON ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADDRESS_ID IS NULL THEN
      SELECT ADDRESS_SEQ.NEXTVAL INTO :NEW.ADDRESS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."ADDRESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDRESS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."ADDRESS_TRG1" 
BEFORE INSERT ON ADDRESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.POSTCODE IS NULL THEN
      SELECT ADDRESS_SEQ1.NEXTVAL INTO :NEW.POSTCODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."ADDRESS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMERS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."CUSTOMERS_TRG1" 
BEFORE INSERT ON CUSTOMERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CUST_ID IS NULL THEN
      SELECT CUSTOMERS_SEQ1.NEXTVAL INTO :NEW.CUST_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."CUSTOMERS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."CUSTOMERS_TRG" 
BEFORE INSERT ON CUSTOMERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."CUSTOMERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."ORDERS_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDER_ID IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."ORDERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RIDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HENSHIN"."RIDER_TRG" 
BEFORE INSERT ON RIDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HENSHIN"."RIDER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."ADMINS" ADD CONSTRAINT "ADMIN_ID" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."ADMINS" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."ADMINS" MODIFY ("ADMIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."ADMINS" MODIFY ("ADMIN_PHONE" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."ADMINS" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARTS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."CARTS" ADD CONSTRAINT "CARTS_PK" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."CARTS" MODIFY ("CART_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."CUSTOMERS" MODIFY ("PHONE_NO" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."CUSTOMERS" MODIFY ("CUST_ID" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."CUSTOMERS" MODIFY ("CUST_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."CUSTOMERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HENSHIN"."CUSTOMERS" MODIFY ("CUST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU_CATEGORY
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."MENU_CATEGORY" ADD CONSTRAINT "MENU_CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."MENU_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_PK" PRIMARY KEY ("ORDER_DETAILS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."ORDER_DETAILS" MODIFY ("ORDER_DETAILS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_STATUS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."ORDER_STATUS" ADD CONSTRAINT "ORDER_STATUS_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."ORDER_STATUS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."PAYMENT" ADD CONSTRAINT "PAYMENT_UK1" UNIQUE ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT_METHOD
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."PAYMENT_METHOD" ADD CONSTRAINT "PAYMENT_METHOD_PK" PRIMARY KEY ("METHOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."PAYMENT_METHOD" MODIFY ("METHOD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RIDER
--------------------------------------------------------

  ALTER TABLE "HENSHIN"."RIDER" ADD CONSTRAINT "RIDER_PK" PRIMARY KEY ("RIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HENSHIN"."RIDER" MODIFY ("RIDER_ID" NOT NULL ENABLE);
